set nu
set background=dark
set t_Co=256
if !has('gui_running')
    " Compatibility for Terminal
    let g:solarized_termtrans=1

    if (&t_Co >= 256 || $TERM == 'xterm-256color')
        " Do nothing, it handles itself.
    else
        " Make Solarized use 16 colors for Terminal support
        let g:solarized_termcolors=16
    endif
else
    set background=light
endif
syntax on
set expandtab
set tabstop=4
set shiftwidth=4
set autoindent
set smartindent
set history=200
colorscheme solarized
set guifont=Source\ Code\ Pro\ Light:h13
