set nu
set background=dark
set t_Co=256
if has("gui_running")
    set background=light
endif
syntax on
set expandtab
set tabstop=4
set shiftwidth=4
set autoindent
set smartindent
set history=200
colorscheme solarized
set guifont=Source\ Code\ Pro\ Light:h13
